apiVersion: v1
kind: Service
metadata:
  name: sofa-rpc-k8s-consumer
  namespace: sofa-rpc-k8s
spec:
  clusterIP: None
  selector:
    app: sofa-rpc-k8s-consumer
  ports:
    - protocol: TCP
      port: 20880
      targetPort: 20880