apiVersion: v1
kind: Namespace
metadata:
  name: sofa-rpc-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sofa-rpc-k8s
  name: sofa-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list", "update", "patch" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sofa-sa
  namespace: sofa-rpc-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sofa-sa-bind
  namespace: sofa-rpc-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sofa-role
subjects:
  - kind: ServiceAccount
    name: sofa-sa